config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :books
  resources :home
  resources :contact, only: [:index, :new, :create]
  devise_for :users
  root to: 'books#index'

  get '/api_book' => 'home#api_book'
  get '/pdf' => 'books#pdf'
  # get '/contact/:id' => 'contact#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  GENRES = ["Romance", "Drama","Horror","Crime","Action","Fantasy","Kids","Biography"]


end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :user_email

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "#{user_email}",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /books or /books.json
  def index
    if(params.has_key?(:genre))
     @books = Book.where(genre: params[:genre]).order("created_at desc")
   else
     @books = Book.all.order("created_at desc")
   end

  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    params = request.query_parameters
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def pdf
    @books = Book.all.order("created_at desc")
    require "prawn"
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        books_array = []
        @books.each do |book|
          if current_user == book.user
            books_array[0] = book.title
            pdf.text books_array.last
          end
        end
        send_data pdf.render,
          filename: "report.pdf",
          type: 'application/pdf'
        end
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :ISBN, :year, :avatar, :genre, :blacklist)
    end

  end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  protect_from_forgery with: :null_session


  def index
    params = request.query_parameters
    @contact = Contact.new(params[:contact])
  end

  def show
  end

  def send_user_email
    @contact = Contact.find(params[:contact])
  end

  def create
    success = 0;
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        @contact = Contact.new
        format.html { render 'info', notice: 'Message was sent!' }
      else
        format.html { render 'index', alert: 'There was something wrong...' }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def api_book
    require 'net/http'
    require 'json'

    name = params[:search]

    @url = "https://www.googleapis.com/books/v1/volumes?q=#{URI.encode(name)}"
    puts @url
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)

    @output = JSON.parse(@response)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def genre(genre)
     if genre == "Romance"
       content_tag :span, "#{genre}", class: "tag is-danger"
     elsif genre == "Drama"
       content_tag :span, "#{genre}", class: "tag is-success"
     elsif genre == "Horror"
       content_tag :span, "#{genre}", class: "tag is-black"
     elsif genre == "Crime"
       content_tag :span, "#{genre}", class: "tag is-info"
     elsif genre == "Action"
       content_tag :span, "#{genre}", class: "tag is-link"
     elsif genre == "Fantasy"
       content_tag :span, "#{genre}", class: "tag is-primary"
     elsif genre == "Kids"
       content_tag :span, "#{genre}", class: "tag is-warning"
     elsif genre == "Biography"
       content_tag :span, "#{genre}", class: "tag is-dark"
     else
       ""
     end
   end
  def user_id(book)
     user_signed_in? && current_user.id == book.user_id
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_form.html.erb
<%= simple_form_for @book, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <div class="field">
      <div class="control">
      <%= f.input :title, required: true, input_html: { class: "input", value: params[:title] }, wrapper: false, label_html: { class: "label" }  %>
      </div>
    </div>

    <!-- <div class="field">
      <div class="control">
        <%# <%= f.input :ISBN, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }  %> %>
      </div>
    </div> -->




    <div class="field">
      <div class="control">
        <%= f.input :description, required: true, input_html: { class: "textarea", value: params[:description] }, wrapper: false, label_html: { class: "label" } %>
      </div>
    </div>

    <div class="columns">
      <div class="field column is-4">
        <div class="control">
          <label class="label">Genre:</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :genre, collection: Book::GENRES, prompt: "Select a genre" %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-briefcase"></i>
            </span>
          </div>
        </div>
      </div>


  <div class="columns">



    <div class="field column">
      <div class="control">
        <%= f.input :year, required: true, input_html: { class: "input" }, wrapper: false, label_html: { class: "label" }  %>
      </div>
    </div>

  </div>

  <div class="columns">
    <div class="field column">
      <div class="control">
        <label class="label">Picture</label>
        <div class="file">
          <label class="file-label">
            <%= f.input :avatar, as: :file, required: false, input_html: { class:"file-input book-avatar" }, label: false, wrapper: false %>
              <span class="file-cta">
                <span class="file-icon"><i class="fa fa-upload"></i></span>
                <span class="file-label">Choose a file…</span>
              </span>
          </label>
        </div>
      </div>
    </div>
    <div class="column">
      <output id="list"></output>
    </div>
  </div>

  <hr />


  <%= f.button :submit, class: "button is-primary is-rounded mv4" %>
<% end %>

app/views/books/_panel.html.erb
<nav class="panel">
  <p class="text-uppercase has-text-gray pv1 f6">filter by genre</p>

  <ul class="mb3 pa0">
    <li class="pv1">
      <%= link_to 'All', books_path, class: "button is-fullwidth is-light is-primary" %>
    </li>

    <li class="pv1">
      <%= link_to 'Action', books_path(genre: "Action"), class: "button is-fullwidth is-link" %>
    </li>

    <li class="pv1">
      <%= link_to 'Biography', books_path(genre: "Biography"), class: "button is-fullwidth is-dark" %>
    </li>

    <li class="pv1">
      <%= link_to 'Crime', books_path(genre: "Crime"), class: "button is-fullwidth is-info" %>
    </li>

    <li class="pv1">
      <%= link_to 'Drama', books_path(genre: "Drama"), class: "button is-fullwidth is-success" %>
    </li>

    <li class="pv1">
      <%= link_to 'Horror', books_path(genre: "Horror"), class: "button is-fullwidth is-black" %>
    </li>

    <li class="pv1">
      <%= link_to 'Fantasy', books_path(genre: "Fantasy"), class: "button is-fullwidth is-primary" %>
    </li>

    <li class="pv1">
      <%= link_to 'Kids', books_path(genre: "Kids"), class: "button is-fullwidth is-warning" %>
    </li>

    <li class="pv1">
      <%= link_to 'Romance', books_path(genre: "Romance"), class: "button is-fullwidth is-danger" %>
    </li>




  </ul>

</nav>

app/views/books/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Editing Book</h1>
        <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</section>

app/views/books/index.html.erb
<div class="columns border-top">

  <div class="column is-2 bg-light">
    <div class="pl3 pr1">
      <%= render 'panel' %>
    </div>
  </div>

  <div class="column is-9 pl6">
    <% @books.each do |book| %>
    <% if current_user.try(:admin) %>
        <% if book.blacklist == true %>
          <div class="columns border-bottom pt4">
            <div class="column is-1">
              <% if !book.avatar.file.nil? %>
                <%= link_to image_tag(book.avatar_url(:thumb), alt: book.user_id, width: 100, height: 100) %>
              <% end %>
            </div>
            <div class="column is-8">
              <h3 class="title is-4 index-title"><%= link_to book.title, book %> - banned </h3>
                <!-- <ul>
                   <%# <li><%= link_to book.user_id %></li> %> %>
                </ul> -->
              <div class="pv2 f6">
                <%= sanitize(book.description.truncate(200, separator: '</p>')) %>
              </div>



              </div>
              <div class="column has-text-right">
                <%= genre(book.genre) %>

              </div>
            </div>

            <% else %>

            <div class="columns border-bottom pt4">
              <div class="column is-1">
                <% if !book.avatar.file.nil? %>
                  <%= link_to image_tag(book.avatar_url(:thumb), alt: book.user_id, width: 100, height: 100) %>
                <% end %>
              </div>
              <div class="column is-8">
                <h3 class="title is-4 index-title"><%= link_to book.title, book %></h3>
                  <!-- <ul>
                     <%# <li><%= link_to book.user_id %></li> %> %>
                  </ul> -->
                <div class="pv2 f6">
                  <%= sanitize(book.description.truncate(200, separator: '</p>')) %>
                </div>



                </div>
                <div class="column has-text-right">
                  <%= genre(book.genre) %>

                </div>
              </div>
        <% end %>




      <%# <% if current_user.try(:admin) %>

      <% else %>

      <% if book.blacklist == true %>
        <div class="columns border-bottom pt4" style="display: none;">
          <div class="column is-1">
            <% if !book.avatar.file.nil? %>
              <%= link_to image_tag(book.avatar_url(:thumb), alt: book.user_id, width: 100, height: 100) %>
            <% end %>
          </div>
          <div class="column is-8">
            <h3 class="title is-4 index-title"><%= link_to book.title, book %></h3>
              <!-- <ul>
                 <%# <li><%= link_to book.user_id %></li> %> %>
              </ul> -->
            <div class="pv2 f6">
              <%= sanitize(book.description.truncate(200, separator: '</p>')) %>
            </div>



            </div>
            <div class="column has-text-right">
              <%= genre(book.genre) %>

            </div>
          </div>

          <% else %>

          <div class="columns border-bottom pt4">
            <div class="column is-1">
              <% if !book.avatar.file.nil? %>
                <%= link_to image_tag(book.avatar_url(:thumb), alt: book.user_id, width: 100, height: 100) %>
              <% end %>
            </div>
            <div class="column is-8">
              <h3 class="title is-4 index-title"><%= link_to book.title, book %></h3>
                <!-- <ul>
                   <%# <li><%= link_to book.user_id %></li> %> %>
                </ul> -->
              <div class="pv2 f6">
                <%= sanitize(book.description.truncate(200, separator: '</p>')) %>
              </div>



              </div>
              <div class="column has-text-right">
                <%= genre(book.genre) %>

              </div>
            </div>
      <% end %>
    <% end %>
    <% end %>

  </div>

</div>

app/views/books/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3">Post new Book</h1>
        <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</section>

app/views/books/pdf.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h2 class="title is-4">Here you can export all your books in PDF</h2>
                <%= link_to 'Check out the PDF', pdf_path(:format => 'pdf') %>
                <hr>  
        <% require "prawn"
        pdf = Prawn::Document.new
        books_array = [] %>
          <% @books.each do |book|
              books_array[0] = book.title
              pdf.text books_array.last
          %>


                <% if current_user == book.user %>
                    <% if book.blacklist == true %>
                      <div class="column">
                        <h3 class="title is-6 index-title">Title: <%= book.title %> <p style="color:red;">Knjiga je na blacklisti!</p></h3>
                        Description:
                        <%= book.description %><br>

                        <h3 class="title is-6 index-title">Year: <%= book.year %></h3>

                        <%= genre(book.genre) %>
                        <hr>
                      </div>

                    <% else %>

                        <div class="column">
                          <h3 class="title is-6 index-title">Title: <%= book.title %></h3>
                          Description:
                          <%= book.description %><br>

                          <h3 class="title is-6 index-title">Year: <%= book.year %></h3>

                          <%= genre(book.genre) %>
                          <hr>
                        </div>
                    <% end %>


                <% end %>


        <% end %>





      </div>
    </div>
  </div>

</section>

app/views/books/show.html.erb
<div class="columns pt4 pb7">
  <div class="column is-7 is-offset-1">

    <p class="f7"><i class="fa fa-clock"></i> Posted <%= time_ago_in_words(@book.created_at) %> ago</p>
    <h1 class="title is-2"><%= @book.title %></h1>
     <h5> <%= genre(@book.genre) %> </h5>
     <ul class="list pb4">


  </ul>

    <!-- <ul class="list pb4">
      <li class="inline-block f6 pr2"><#%= job_type(@job.job_type) %></li>
      <li class="inline-block f6 ph2"><i class="fa fa-pin"></i> <#%= @job.location %></li>
      <#% if @job.remote_ok? %>
        <li class="inline-block f6 ph2"><i class="fa fa-wifi"></i> Remote Job</li>
      <#% end %>
    </ul> -->

    <div class="content text-serif f4">
      <%= @book.description.html_safe %>
    </div>

  <%= form_with url: "/contact", method: :post do |f| %>
      <div class="field" style="display:none">
        <div class="hidden">
          <%= f.text_field :user_email, class:"input", value: @book.user.email %>
        </div>
      </div>

      <div class="field" style="display:none">
        <div class="hidden">
          <%= f.text_field :email, class:"input", value: current_user.email %>
        </div>
      </div>

      <div class="field" style="display:none">
        <div class="hidden">
          <%= f.text_field :name, class:"input", value: current_user.name %>
        </div>
      </div>
      <%= f.submit "I am interested", class: "button is-primary is-rounded mv4 is-fullwidth is-large" %>
  <% end %>
   <%# link_to 'I am interested', contact_index_path(:user_email => @book.user.email, :user => current_user.email, :username => current_user.name ), :method => :post %>
  <%# <%= mail_to @book.user.email, 'I am interested', class: "button is-rounded is-large is-fullwidth is-primary" %>
  </div>

  <div class="column is-2 is-offset-1 has-text-centered">

    <% if !@book.avatar.file.nil? %>
      <%=  image_tag(@book.avatar_url(:thumb), alt:"", class: "has-text-centered") %>
    <% end %>

    <div>
      <b> Book title </b>
    <p>  <h5 class="is-5 has-text-centered"><%=  @book.title %></h5> </p>
      </div>

      <div>
        <b> Genre </b>
      <p>  <h5 class="is-5 has-text-centered"><%=  @book.genre %></h5> </p>
        </div>

      <div>
          <b> Year </b>
        <p>  <h5 class="is-5 has-text-centered"><%=  @book.year %></h5> </p>
          </div>






     <!-- link_to 'Apply to this job', @job.apply_url, class:"button is-rounded is-fullwidth is-link" %> -->
    <!-- if current_user.try(:admin) || book_seller(@book) -->
    <% if current_user == @book.user || current_user.try(:admin) %>
      <ul class="pv3">
        <li class="pv1 f6">Admin controls: </li>
        <li class="pv1 inline-block">
          <%= link_to 'View', @book, class: 'button is-small  is-outlined is-primary' %></li>
        <li class="pv1 inline-block">
          <%= link_to 'Edit', edit_book_path(@book), class: 'button is-small  is-outlined is-primary' %></li>
        <li class="pv1 inline-block">
          <%= button_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small  is-outlined is-primary' %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/contact/_contact_form.html.erb
<div class="section">
  <div class="container">
  <div class="columns is-centered">

    <div class="column is-7">

    <h2 class="title is-2">Contact with the book seller</h2>

    <%= form_for @contact, url: contact_index_path, remote: true do |f| %>

    <div class="field">
      <div class="control">
      <%= f.text_field  :name, required: true, class:"input", value: params[:name]%>
      </div>
    </div>

    <div class="field" style="display:none">
      <div class="control">
      <%= f.text_field :email, required: true, class:"input", value: params[:email]%>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.text_area :message, required: true, class: "textarea", placeholder: "Send me a message"%>
      </div>
    </div>

    <div class="field" style="display:none">
      <div class="hidden">
        <%= f.text_field :user_email, required: true, class:"input", value: params[:user_email] %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.submit 'Send Message', class: "button is-primary is-rounded mv4" %>
      </div>
    </div>

    <% end %>
      <br />
    </div>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<div id="contact">
    <%= render 'contact_form' %>
</div>

app/views/contact/info.html.erb
<div class="columns border-top">

  <div class="column is-9 pl6">
    <%= link_to 'Go back', books_path, class: 'button is-small is-primary' %>
  </div>

</div>

app/views/home/_form.html.erb
<%= form_with(url: '/api_book', method: 'get', local: true) do |form|%>
  <div class="form-group">
    <%= form.text_field :search, required: true, class:"input is-primary" %>
  </div>

  <%= form.submit 'Submit', class: "button is-primary is-rounded mv4" %>
<% end %>

app/views/home/api_book.html.erb
<div class="columns pt4 pb7">
  <div class="column is-7 is-offset-1">



<% if @output['items'].nil? %>
  <p class="title"> I'm sorry. This book doesn't exist in our data... Check please again the spelling :( </p>
  <%= link_to 'Try Again', home_index_path, class: "button is-rounded is-primary" %>
<% else %>
<strong class="title">This are the results: </strong>
  <% @output['items'].each do |item| %>
  <% title = item['volumeInfo']['title'] %>
  <% description = item['volumeInfo']['description'] %>
  <% publishedDate = item['volumeInfo']['publishedDate'] %>
  <div class="tile is-parent is-vertical">
  <div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><strong>Title: </strong> <%= item['volumeInfo']['title'] %></p>
      </div>
    </div>

    <div class="content">
      <p><strong>Language: </strong> <%= item['volumeInfo']['language'] %></p>
      <p style="max-width: 100ch; display:inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
        <strong>Description: </strong> <%= item['volumeInfo']['description'] %>
      </p>
      <br>
      <time><strong>Published Date: </strong> <%= item['volumeInfo']['publishedDate'] %></time>
    </div>
    <%= link_to 'Choose this', controller: 'books', action: 'new', title: title, description: description %>
  </div>

  </div>
  </div>


  <% end %> <!--each.do -->

<% end %> <!--else -->

</div>
</div>

app/views/home/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1 class="title is-3"></h1>
        <%= render "form" %>
      </div>
    </div>
  </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.configuration.application_name %></title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', "https://js.stripe.com/v2/", "https://js.stripe.com/v3/", 'data-turbolinks-track': 'reload' %>



  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

     <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5"><%= Rails.configuration.application_name %></h1>
        <% end  %>
        <div class="navbar-burger burger" data-target="navbar">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to 'New Book', home_index_path, class: "navbar-item button is-primary is-rounded" %>
              </p>


              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Export all my books", pdf_path, class:"navbar-item" %>
                  <%= button_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>
            <p class="control">
              <%= link_to "Sign In", new_user_session_path, class:"navbar-item button" %>
            </p>
            <p class="control">
              <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button"%>
            </p>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </nav>


  <%= yield %>


  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
      Booksy 2021
        </p>
      </div>
    </div>
  </footer>

  </body>
</html>